Repository WMD-group/SMACT, pull requests merged in 2025-01, with the labels that each got.

#360 Make the Materials Project tests optional
  .github/workflows/check-live-links.yml
  smact/tests/test_structure.py
  smact/tests/test_utils.py
Labels: bug, tests

#361 Include crystal space utils in package build
  pyproject.toml
  setup.py
Labels: bug

#363 Drop setup.py
  pyproject.toml
  setup.py
Labels: pkg, housekeeping

#365 Fix the MP URL to ensure tests run
  smact/tests/test_structure.py
  smact/tests/test_utils.py
Labels: bug, tests, housekeeping

#367 SMACT Metallicity Handling Enhancements
  docs/examples.rst
  docs/examples/metallicity.ipynb
  docs/smact.metallicity.rst
  docs/smact.rst
  docs/tutorials.rst
  docs/tutorials/metallicity_classification.ipynb
  pyproject.toml
  requirements.txt
  smact/metallicity.py
  smact/screening.py
  smact/tests/test_metallicity.py
  smact/tests/test_structure.py
Labels: enhancement, python, feature
